[package]
name = "native-lottery"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.17.15"
borsh = "0.10.4"
borsh-derive = "0.10.4"
thiserror = "1.0"
